stage: sft
do_train: true
do_eval: true
predict_with_generate: true
model_name_or_path: Qwen/Qwen2.5-Coder-3B-Instruct
ref_model: Qwen/Qwen2.5-Coder-7B-Instruct
ref_model_adapters: results/qwen2.5_coder/teacher_lora
dataset: cypher_prepared_train
eval_dataset: cypher_prepared_eval
dataset_dir: data/llamafactory
template: qwen
cutoff_len: 892
packing: false
ignore_pad_token_for_loss: true
preprocessing_num_workers: 1
dataloader_num_workers: 1
dataloader_drop_last: false
finetuning_type: lora
lora_target: all
lora_rank: 32
lora_alpha: 64
lora_dropout: 0.1
train_on_prompt: false
distill_method: amid
kd_ratio: 1.0
amid_div_name: ab
amid_div_order: pr
amid_alpha: 0.5
amid_lam: 0.5
output_dir: results/qwen2.5_coder/amid
overwrite_output_dir: true
per_device_train_batch_size: 1
per_device_eval_batch_size: 8
gradient_accumulation_steps: 16
learning_rate: 0.0001
num_train_epochs: 5
optim: adamw_torch
lr_scheduler_type: cosine_with_min_lr
lr_scheduler_kwargs:
  min_lr_rate: 0.001
warmup_steps: 0
weight_decay: 0.01
max_grad_norm: 1.0
logging_steps: 20
save_strategy: epoch
eval_strategy: epoch
seed: 42
bf16: true
deepspeed: configs/deepspeed/ds_config_bf16.json
report_to: none
