stage: sft
do_train: true
do_eval: true
predict_with_generate: true
model_name_or_path: Qwen/Qwen2.5-Coder-3B-Instruct
model_revision: 488639f1ff808d1d3d0ba301aef8c11461451ec5
ref_model: results/qwen2.5_coder/teacher_full
dataset: cypher_prepared_train
eval_dataset: cypher_prepared_eval
dataset_dir: data/llamafactory
template: qwen
cutoff_len: 892
packing: false
ignore_pad_token_for_loss: true
preprocessing_num_workers: 1
dataloader_num_workers: 1
dataloader_drop_last: false
finetuning_type: full
train_on_prompt: false
distill_method: adaptive_srkl
kd_ratio: 0.6
skew_alpha: 0.1
student_gen: true
rollout_context_length: 797
gen_top_p: 1.0
init_threshold: 0.0
loss_eps: 0.1
capacity: 1000
replay_ratio: decreasing
output_dir: results/qwen2.5_coder/distillm_adaptive_srkl
overwrite_output_dir: true
per_device_train_batch_size: 2
per_device_eval_batch_size: 8
gradient_accumulation_steps: 8
learning_rate: 0.00002
num_train_epochs: 5
optim: adamw_torch
lr_scheduler_type: cosine_with_min_lr
lr_scheduler_kwargs:
  min_lr_rate: 0.001
warmup_ratio: 0.05
weight_decay: 0.01
max_grad_norm: 1.0
logging_steps: 20
save_strategy: epoch
save_total_limit: null
eval_strategy: epoch
seed: 42
bf16: true
deepspeed: configs/deepspeed/ds_config_bf16.json
report_to: none
do_sample: true
top_k: 0
top_p: 0.95
temperature: 0.5
repetition_penalty: 1.0
