stage: sft
do_train: true
do_eval: true
predict_with_generate: true

model_name_or_path: meta-llama/Llama-3.2-1B-Instruct
ref_model: meta-llama/Meta-Llama-3-8B-Instruct
ref_model_adapters: results/llama3/teacher_lora
dataset: cypher_prepared_train
eval_dataset: cypher_prepared_eval
dataset_dir: data/llamafactory
template: llama3
cutoff_len: 899
packing: false
ignore_pad_token_for_loss: true
preprocessing_num_workers: 1
dataloader_num_workers: 1
dataloader_drop_last: false

finetuning_type: lora
lora_target: all
lora_rank: 32
lora_alpha: 64
lora_dropout: 0.1
train_on_prompt: false
mask_history: false

distill_method: amid
kd_ratio: 1.0
amid_div_name: ab
amid_div_order: pr
amid_alpha: 0.5
amid_lam: 0.5

output_dir: results/llama3/amid
overwrite_output_dir: true
per_device_train_batch_size: 16
per_device_eval_batch_size: 32
gradient_accumulation_steps: 1
gradient_checkpointing: false
learning_rate: 0.0001
num_train_epochs: 5
optim: adamw_torch
adam_beta1: 0.9
adam_beta2: 0.999
adam_epsilon: 1.0e-8
lr_scheduler_type: cosine_with_min_lr
lr_scheduler_kwargs:
  min_lr_rate: 0.001
warmup_steps: 0
weight_decay: 0.01
max_grad_norm: 1.0
logging_strategy: steps
logging_steps: 20
save_strategy: epoch
eval_strategy: epoch
seed: 42
bf16: true
fp16: false
deepspeed: configs/deepspeed/ds_config_bf16.json
report_to: none
