stage: sft
do_train: true
do_eval: true
predict_with_generate: true

model_name_or_path: Qwen/Qwen3-0.6B
ref_model: Qwen/Qwen3-4B-Instruct-2507
ref_model_adapters: results/qwen3/teacher_lora
dataset: cypher_prepared_train
eval_dataset: cypher_prepared_eval
dataset_dir: data/llamafactory
template: qwen3_nothink
cutoff_len: 892
packing: false
ignore_pad_token_for_loss: true
preprocessing_num_workers: 1
dataloader_num_workers: 1
dataloader_drop_last: false

finetuning_type: lora
lora_target: all
lora_rank: 32
lora_alpha: 64
lora_dropout: 0.1
train_on_prompt: false
mask_history: false

distill_method: fkl
kd_ratio: 0.6

output_dir: results/qwen3/fkl
overwrite_output_dir: true
per_device_train_batch_size: 2
per_device_eval_batch_size: 16
gradient_accumulation_steps: 8
gradient_checkpointing: false
learning_rate: 0.0001
num_train_epochs: 5
optim: adamw_torch
adam_beta1: 0.9
adam_beta2: 0.999
adam_epsilon: 1.0e-8
lr_scheduler_type: cosine_with_min_lr
lr_scheduler_kwargs:
  min_lr_rate: 0.001
warmup_steps: 0
weight_decay: 0.01
max_grad_norm: 1.0
logging_strategy: steps
logging_steps: 20
save_strategy: epoch
eval_strategy: epoch
seed: 42
bf16: true
fp16: false
deepspeed: configs/deepspeed/ds_config_bf16.json
report_to: none
